
PROJECT_OBJDIR := $(CURDIR)/obj
PROJECT_DISTDIR := $(CURDIR)/dist
PROJECT_MKDIR := $(CURDIR)/mk

ALL_PREREQUISITES := app test/here

all: $(ALL_PREREQUISITES)

app: 
	$(MAKE) -C "$(CURDIR)/$@" -I "$(PROJECT_MKDIR)" "PROJECT_OBJDIR=$(PROJECT_OBJDIR)" "PROJECT_DISTDIR=$(PROJECT_DISTDIR)"

test/here: 
	$(MAKE) -C "$(CURDIR)/$@" -I "$(PROJECT_MKDIR)" "PROJECT_OBJDIR=$(PROJECT_OBJDIR)" "PROJECT_DISTDIR=$(PROJECT_DISTDIR)"

.PHONY: $(ALL_PREREQUISITES)

